server:
  port: 8080
spring:
  application:
    name: homestay-service
  main:
    allow-circular-references: true
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://${hm.db.host}:3306/nature_education_activity?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: ${hm.db.pw}

logging:
  level:
    com:
      tanyde:
        mapper: debug
        service: info
        controller: info

homestay:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: ittanyde
    # 设置jwt过期时间（2.9亿年awa）
    admin-ttl: 9223372036854775
    # 设置前端传递过来的令牌名称
    admin-token-name: token
    user-secret-key: ittanyde
    user-ttl: 9223372036854775
    user-token-name: authentication
